# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', editable=False)),
                ('image', models.ImageField(default='', upload_to='Thumb')),
            ],
        ),
        migrations.CreateModel(
            name='short',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longUrl', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
