# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='shortUrl',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
