# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0009_auto_20200203_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='link',
            field=models.CharField(blank=True, default='Link', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='shortUrl',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
