# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0010_auto_20200203_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short',
            old_name='link',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='short',
            old_name='shortUrl',
            new_name='Token',
        ),
    ]
