# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0011_auto_20200203_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
